"""add_description_and_agent_tools

Revision ID: 2b43f59dae43
Revises: 547bbc222aad
Create Date: 2026-04-25 17:36:08.009340

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b43f59dae43"
down_revision: Union[str, Sequence[str], None] = "547bbc222aad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "tb_agent_tools",
    sa.Column("agent_id", sa.String(), nullable=False),
    sa.Column("tool_id", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(
      ["agent_id"],
      ["tb_agents.id"],
    ),
    sa.ForeignKeyConstraint(
      ["tool_id"],
      ["tb_tools.id"],
    ),
    sa.PrimaryKeyConstraint("agent_id", "tool_id"),
  )
  op.add_column("tb_agents", sa.Column("description", sa.String(), server_default="", nullable=False))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("tb_agents", "description")
  op.drop_table("tb_agent_tools")
  # ### end Alembic commands ###
