"""create_tb_tools

Revision ID: 547bbc222aad
Revises: 66689209b2ce
Create Date: 2026-04-25 16:47:11.997211

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '547bbc222aad'
down_revision: Union[str, Sequence[str], None] = '66689209b2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_tools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO tb_tools (id, name) VALUES ('d4f3b2a1-1234-5678-abcd-ef0123456789', '웹 검색(web search)')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_tools')
    # ### end Alembic commands ###
