"""add assigned_agent_name to tb_todos

Revision ID: e7de1898f4f9
Revises: 22c45b15bdab
Create Date: 2026-04-18 14:14:44.770560

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7de1898f4f9"
down_revision: Union[str, Sequence[str], None] = "22c45b15bdab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("tb_todos", sa.Column("assigned_agent_name", sa.String(), nullable=True))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("tb_todos", "assigned_agent_name")
  # ### end Alembic commands ###
